{
  description = "NixOS – ThinkPad P15 (dendritic pattern)";

  inputs = {
    # ── NixOS unstable channel ───────────────────────────────────────
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # ── sops-nix for secrets management ──────────────────────────────
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, sops-nix, ... }:
  {
    nixosConfigurations.thinkpad-p15 = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # ── Hardware scan (generated by nixos-generate-config) ───────
        ./hardware-configuration.nix

        # ── Dendritic module tree ────────────────────────────────────
        ./modules

        # ── sops-nix module ──────────────────────────────────────────
        sops-nix.nixosModules.sops
      ];
    };
  };
}
